### ISSUE TITLE
Nerd font

### ISSUE THREAD

**Issue by Tyrn** [gquittet/dotfiles#2]
Hi,

What kind of a nerd font your Neovim setup depends on?

Sorry, I can't figure it out myself.

**Comment by gquittet** [comment]
Whichever font you like 🙂 

I use FuraCodeNerdFontComplete-Regular

**Comment by gquittet** [comment]
@Tyrn Have I answer to your question? 🙂

**Comment by Tyrn** [comment]
I can't really say. I've got two Neovim installations based on your setup: Manjaro (host) and Raspberry Pi Desktop (vbox). It's fine with Manjaro, and no wonder: the monster (1.5G) package `nerd-fonts-complete` takes care of it all. With Raspberry still no cigar:

```
$ fc-list | grep Fura
/home/pi/.fonts/Fura Code Regular Nerd Font Complete.otf: FuraCode Nerd Font:style=Regular
```
I'm not dead sure i'm doing it quite right, though. Maybe I'm overlooking something.

**Comment by Tyrn** [comment]
Yes, this is kinda my fault: Raspbian's Terminal can't cope with fancy fonts. Konsole can, but the Raspbian can't really cope with Konsole :) . This is another matter...

**Comment by Tyrn** [comment]
BTW, what LaTeX toolchain do you employ? Your vimtex setup consists of one line exactly, which is remarkable.
